[package]
name = "aws-nitro-enclaves-image-format"
version = "0.3.0"
authors = ["The AWS Nitro Enclaves Team <aws-nitro-enclaves-devel@amazon.com>"]
edition = "2018"
license = "Apache-2.0"
description = "This library provides the definition of the enclave image format (EIF) file used in AWS Nitro Enclaves."
repository = "https://github.com/aws/aws-nitro-enclaves-image-format"
readme = "README.md"
keywords = ["Nitro", "Enclaves", "AWS"]
rust-version = "1.68"

[dependencies]
sha2 = "0.9.5"
serde = { version = ">=1.0", features = ["derive"] }
serde_json = "1.0"
num-traits = "0.2"
num-derive = "0.4"
byteorder = "1.3"
clap = "4.5"
hex = "0.4"
crc = "3.0"
aws-nitro-enclaves-cose = { git = "https://github.com/andrcmdr/aws-nitro-enclaves-cose.git", branch = "main", version = "0.5.2", features = ["key_openssl_pkey", "key_kms"] }
openssl = "0.10.70"
serde_cbor = "0.11"
chrono = { version = "0.4", default-features = false, features = ["clock"]}

[workspace]
members = [
    ".",  # aws-nitro-enclaves-image-format
    "eif_build",  # The eif_build CLI tool
    "eif_extract",  # The eif_extract CLI tool
]
